server:
  port: 8080
  servlet:
    context-path: /tiny-job
spring:
  profiles:
    active: h2
  resources:
    static-locations: classpath:static/
  thymeleaf:
    mode: HTML5
    cache: false
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  configuration:
    map-underscore-to-camel-case: true
tiny-job:
  triggerPollSize: 100
  log:
    level: debug
