spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tinyjob;MODE=MySQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
pagehelper:
  helperDialect: h2
